/* Bundle spoken audio for every character.

   Why bundle rather than use the browser's speech engine: speechSynthesis is
   blocked in the cross-origin frame artifacts are embedded in, and several
   voices macOS lists have no voice data and produce silence. Bundled clips
   play through a plain <audio> element, which works there.

   Needs macOS `say` and `afconvert`.  Run: node tools/make-audio.mjs */

import { execFileSync } from 'child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync, statSync } from 'fs';
import { fileURLToPath } from 'url';
import { join } from 'path';
import { tmpdir } from 'os';

const VOICE = process.argv[2] || 'Tingting';
const BITRATE = '24000';
const MIN_SECONDS = 0.15;          /* shorter than this means the voice is mute */

const root = fileURLToPath(new URL('../', import.meta.url));
const { HQ, MENU, INTERESTS, FESTIVALS } = new Function(
  readFileSync(join(root, 'js/data.js'), 'utf8') + '\nreturn {HQ,MENU,INTERESTS,FESTIVALS};')();
const work = mkdtempSync(join(tmpdir(), 'hq-audio-'));

/* Every character the app can be asked to say — not just the taught ones.

   This used to bundle HQ only, which left the 225 characters that appear in
   example words, sentences and the menu without clips: 金 in 现金, 第 in 第一,
   儿 in 女儿. One missing clip made sayPhrase give up on the whole word and
   fall through to the system voice, so tapping 现金 was silent on any machine
   without a Chinese voice installed. A word you can see is a word you can
   tap, so everything visible gets recorded. */
const speakable = () => {
  const out = new Set();
  const add = s => [...String(s || '')].forEach(c => { if (/[\u4e00-\u9fff]/.test(c)) out.add(c); });
  HQ.forEach(ch => { add(ch.c); ch.words.forEach(w => add(w[0])); add(ch.sent[0]); });
  if (MENU) {
    add(MENU.title); add(MENU.name);
    MENU.sections.forEach(s => { add(s.head); s.items.forEach(i => { add(i[0]); if (i[4]) add(i[4][0]); }); });
    (MENU.phrases || []).forEach(p => add(p[0]));
    if (MENU.specials) {
      add(MENU.specials.head);
      (MENU.specials.items || []).forEach(i => add(i[0]));
      if (MENU.specials.note) add(MENU.specials.note[0]);
    }
  }
  Object.values(INTERESTS || {}).forEach(c => c.words.forEach(w => add(w[0])));
  (FESTIVALS || []).forEach(f => f.words.forEach(w => add(w[0])));
  return [...out];
};

const clips = {};
const silent = [];
let bytes = 0;

/* ---------- characters the voice reads with a different reading ----------

   Ten characters here are taught with a colloquial reading that is not the
   dictionary default — 文白異讀, the literary/spoken split — and `say` reads a
   character in isolation, so it uses the default. The clip then teaches a
   different word from the one on the card.

   Established by comparison, which is the only way to check this without
   listening: synthesise the character and a homophone of the reading you
   expect, and compare the audio. Identical bytes mean `say` used that reading.

     行 == 恆    say uses hang4;   the card teaches haang4   wrong
     喎 == 蛙    say uses waa1;    the card teaches wo3      wrong
     聽 != 廳    say is not teng1; the card teaches teng1    wrong
     朝 != 招    say is not ziu1;  the card teaches ziu1     wrong
     呀 == 亞    say uses aa3;     the card teaches aa3      fine
     返 == 番    say uses faan1;   the card teaches faan1    fine

   Where a common homophone of the taught reading exists the clip is recorded
   from that instead: same syllable, same tone, a character the voice is sure
   of. Both below are confirmed by CC-Canto. */
const SAY_AS = {
  "聽": "廳",     /* teng1 — 廳 is teng1 and nothing else */
  "朝": "招"      /* ziu1  — 招 is ziu1 and nothing else */
};

/* Readings no single character can supply, because they belong to that
   character alone. The clip is the voice's own reading and does not match the
   card. Recording the word each appears in would fix it, and this bundle is
   per character — so it is written down rather than quietly lived with. */
const UNFIXED = ["名", "呢", "坐", "平", "行", "喎"];

const WANTED = speakable();
process.stdout.write(`speaking ${WANTED.length} characters as ${VOICE}`);
process.stdout.write(` (${HQ.length} taught, ${WANTED.length - HQ.length} from words, sentences and the menu)\n`);
WANTED.forEach((c, i) => {
  const aiff = join(work, 'c.aiff'), m4a = join(work, 'c.m4a');
  execFileSync('say', ['-v', VOICE, '-o', aiff, SAY_AS[c] || c]);
  const info = execFileSync('afinfo', [aiff]).toString();
  const dur = parseFloat((info.match(/estimated duration: ([\d.]+)/) || [])[1] || '0');
  if (dur < MIN_SECONDS) { silent.push(c); return; }
  execFileSync('afconvert', ['-f', 'm4af', '-d', 'aac', '-b', BITRATE, aiff, m4a]);
  clips[c] = readFileSync(m4a).toString('base64');
  bytes += statSync(m4a).size;
  if ((i + 1) % 50 === 0) process.stdout.write(`  ${i + 1}/${WANTED.length}\n`);
});
rmSync(work, { recursive: true, force: true });

const out = `/* Spoken audio, generated by tools/make-audio.mjs (voice: ${VOICE}).
   The browser's speech engine is unavailable inside an embedded frame, so the
   clips ship with the page. Regenerate after adding characters. */
window.HQ_AUDIO = ${JSON.stringify(clips)};
`;
writeFileSync(join(root, 'js/audio.js'), out);

const swapped = Object.keys(SAY_AS).filter(c => WANTED.includes(c));
if (swapped.length) console.log(`\nread from a homophone: ${swapped.map(c => c + ' \u2192 ' + SAY_AS[c]).join(', ')}`);
const stillOff = UNFIXED.filter(c => WANTED.includes(c));
if (stillOff.length) console.log(`the voice's own reading, not the card's: ${stillOff.join(' ')}`);
console.log(`\nbundled ${Object.keys(clips).length} clips`);
if (silent.length) console.log(`no audio for: ${silent.join(' ')}`);
console.log(`audio ${(bytes / 1024 / 1024).toFixed(2)} MB → js/audio.js ${(out.length / 1024 / 1024).toFixed(2)} MB`);
